<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="197MUMMB43721" failures="1" tests="5" name="ChatbotTest" time="71.219" errors="0" timestamp="2024-01-31T14:43:58 IST">
  <testcase classname="com.chatbot.ChatbotTest" name="verifyThatUserCanOrderPizzas" time="33.698"/>
  <testcase classname="com.chatbot.ChatbotTest" name="verifyBotResponseWhenPizzaTypeIsNotListed" time="7.281">
    <failure type="java.lang.AssertionError" message="expected [i am sorry ,  could&amp;apos;nt Understand , Try Again .] but found [i am sorry , I could&amp;apos;nt Understand , Try Again .]">
      <![CDATA[java.lang.AssertionError: expected [i am sorry ,  could'nt Understand , Try Again .] but found [i am sorry , I could'nt Understand , Try Again .]
at com.chatbot.ChatbotTest.verifyBotResponseWhenPizzaTypeIsNotListed(ChatbotTest.java:144)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- verifyBotResponseWhenPizzaTypeIsNotListed -->
  <testcase classname="com.chatbot.ChatbotTest" name="verifyThatUserCanCancelOrder" time="11.887"/>
  <testcase classname="com.chatbot.ChatbotTest" name="verifyThatUserCanResetContextIinBetweenOrder" time="2.873"/>
  <testcase classname="com.chatbot.ChatbotTest" name="verifyBotResponseBySendingOneAlphabeticCharacter" time="8.704"/>
</testsuite> <!-- ChatbotTest -->
